version: "3.9"
services:
  web:
    # image: "webapp:latest"
    build: webapp
    environment:
      DATABASE_URL: "postgres://postgres:password@plant_database:5432/postgres"
    ports:
      - "443:443"
      - "80:80"
    links:
      - "postgres:plant_database"
    volumes:
      - /home/wedmisten/certs:/certs
  postgres:
    build: plant_db
    # image: "plant_db:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
