version: "3.9"
services:
  web:
    # image: "webapp:latest"
    build: webapp
    ports:
      - "5000:5000"
    links:
      - "postgres:plant_database"
  postgres:
    build: plant_db
    # image: "plant_db:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
